# This is a template for configuration file used by switch
# This is a test for the configuration file for the get_inputs
# For connecting to the database we need add the .env file where we place the environment
# variables for your own computer
---

# ------------------
# General config
# ------------------
inputs_dir: inputs

# --------------------------------
# Config used by switch get_inputs
# --------------------------------
get_inputs:
  # Database information
  schema: switch

  # Scenario configuration
  scenario_id: <FILL_IN>
  #  the following parameters are optional and will override the defaults for that scenario
  #  this should only be used for preliminary exploration of scenarios or for testing
  #  if a scenario is part of research, it should be included in the database as a row in the scenarios table.
  #  study_timeframe_id:
  #  time_sample_id:
  #  demand_scenario_id:
  #  fuel_simple_price_scenario_id:
  #  generation_plant_scenario_id:
  #  generation_plant_cost_scenario_id:
  #  generation_plant_existing_and_planned_scenario_id:
  #  hydro_simple_scenario_id:
  #  carbon_cap_scenario_id:
  #  supply_curves_scenario_id:
  #  regional_fuel_market_scenario_id:
  #  rps_scenario_id:
  #  enable_dr:
  #  enable_ev:
  #  transmission_base_capital_cost_scenario_id:
  #  ca_policies_scenario_id:
  #  enable_planning_reserves:
  #  generation_plant_technologies_scenario_id:
  #  variable_o_m_cost_scenario_id:
# add_storage was used by Martin when studying LDES
# you likely don't need to use these parameters
# they won't impact your runs
add_storage:
  costs_scenario: 0
  constant_scenario: 0
  plants_scenario: 0